#!/usr/bin/env python3
"""
Training Data Export Engine (Memory Optimized)
Exports training, validation, and test datasets generated by prepare_training_data.py
into production-ready Apache Parquet and CSV formats in database/exports/.
"""

import os
import gc
import sys
import sqlite3
import argparse
import pandas as pd
import numpy as np
from prepare_training_data import build_ml_features


def export_training_datasets(
    db_path: str = "data/weather_app.db",
    export_dir: str = "database/exports",
    dataset_name: str = "karnataka_weather_ml_v1",
    train_pct: float = 0.70,
    val_pct: float = 0.15
) -> dict:
    if not os.path.exists(db_path):
        print(f"[-] Error: Database not found at {db_path}", file=sys.stderr)
        sys.exit(1)
        
    os.makedirs(export_dir, exist_ok=True)
    print(f"[+] Loading and preparing data for export from {db_path}...")
    
    conn = sqlite3.connect(db_path, timeout=60.0)
    query = """
        SELECT 
            t.record_id,
            l.district,
            g.grid_point_id,
            g.latitude,
            g.longitude,
            t.valid_time_utc,
            t.timestamp_epoch,
            t.year,
            t.month,
            t.day,
            t.hour,
            t.t2m_deg_c,
            t.d2m_deg_c,
            t.msl_hpa,
            t.tp_mm,
            t.relative_humidity_pct,
            t.dew_point_depression_c,
            t.quality_flag
        FROM tabular_weather_records t
        JOIN grid_points g ON t.grid_point_id = g.grid_point_id
        JOIN locations l ON g.location_id = l.location_id
        WHERE t.t2m_deg_c IS NOT NULL AND t.tp_mm IS NOT NULL
        ORDER BY t.timestamp_epoch ASC, g.grid_point_id ASC
    """
    raw_df = pd.read_sql_query(query, conn)
    ml_df = build_ml_features(raw_df)
    del raw_df
    gc.collect()
    
    # Downcast float64 to float32 to reduce memory footprint by 50%
    float_cols = ml_df.select_dtypes(include=["float64"]).columns
    for c in float_cols:
        ml_df[c] = ml_df[c].astype(np.float32)
        
    # Chronological Splitting boundaries
    unique_timestamps = sorted(ml_df["timestamp_epoch"].unique())
    n_times = len(unique_timestamps)
    
    train_idx_end = int(n_times * train_pct)
    val_idx_end = int(n_times * (train_pct + val_pct))
    
    train_t_end = unique_timestamps[train_idx_end - 1]
    val_t_end = unique_timestamps[val_idx_end - 1]
    
    split_definitions = [
        ("train", ml_df["timestamp_epoch"] <= train_t_end),
        ("validation", (ml_df["timestamp_epoch"] > train_t_end) & (ml_df["timestamp_epoch"] <= val_t_end)),
        ("test", ml_df["timestamp_epoch"] > val_t_end)
    ]
    
    exported_files = {}
    print(f"\n[+] Exporting partitions to {export_dir}:")
    
    for split_name, mask in split_definitions:
        split_df = ml_df[mask].copy()
        n_rows = len(split_df)
        
        csv_filename = f"{dataset_name}_{split_name}.csv"
        parquet_filename = f"{dataset_name}_{split_name}.parquet"
        
        csv_path = os.path.join(export_dir, csv_filename)
        parquet_path = os.path.join(export_dir, parquet_filename)
        
        # Export Parquet first (fast and compact)
        split_df.to_parquet(parquet_path, index=False, engine="pyarrow", compression="snappy")
        parquet_mb = round(os.path.getsize(parquet_path) / (1024 * 1024), 2)
        
        # Export CSV in chunks to avoid memory spikes
        split_df.to_csv(csv_path, index=False, chunksize=25000, float_format="%.4f")
        csv_mb = round(os.path.getsize(csv_path) / (1024 * 1024), 2)
        
        print(f"    - [{split_name.upper():<10}] {n_rows:>7,} rows | Parquet: {parquet_mb:>5.2f} MB | CSV: {csv_mb:>5.2f} MB")
        
        exported_files[split_name] = {
            "rows": n_rows,
            "csv_path": csv_path,
            "csv_size_mb": csv_mb,
            "parquet_path": parquet_path,
            "parquet_size_mb": parquet_mb
        }
        
        del split_df
        gc.collect()
        
    # Update paths in database
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE ml_training_datasets
        SET export_csv_path = ?,
            export_parquet_path = ?
        WHERE dataset_name = ?
    """, (
        exported_files["train"]["csv_path"],
        exported_files["train"]["parquet_path"],
        dataset_name
    ))
    
    for sname in ["train", "validation", "test"]:
        cursor.execute("""
            UPDATE ml_dataset_splits
            SET file_path_csv = ?,
                file_path_parquet = ?
            WHERE dataset_id = (SELECT dataset_id FROM ml_training_datasets WHERE dataset_name = ?)
              AND split_name = ?
        """, (
            exported_files[sname]["csv_path"],
            exported_files[sname]["parquet_path"],
            dataset_name,
            sname
        ))
        
    conn.commit()
    conn.close()
    
    print("\n[+] All dataset splits successfully exported and cataloged!")
    return exported_files


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export ML datasets to CSV and Parquet formats.")
    parser.add_argument("--db", default="data/weather_app.db", help="Path to SQLite database file")
    parser.add_argument("--export-dir", default="database/exports", help="Directory for exported files")
    parser.add_argument("--name", default="karnataka_weather_ml_v1", help="Dataset identifier name")
    args = parser.parse_args()
    
    export_training_datasets(args.db, args.export_dir, args.name)
